extension_dir="C:\Users\75206\AppData\Local\Microsoft\WinGet\Packages\PHP.PHP.8.1_Microsoft.Winget.Source_8wekyb3d8bbwe\ext"
extension=mbstring
extension=mysqli
extension=pdo_mysql
extension=openssl
extension=curl
extension=gd
extension=pdo_sqlite
extension=sqlite3
date.timezone=Asia/Shanghai
