<?php
if(!defined('IN_SDCMS')) exit;
return array (
  'index.php' => '首页',
  'book.php' => '留言',
  'foot.php' => '底部',
  'head.php' => '头部',
  'taglist.php' => '标签明细',
  'tags.php' => '标签列表',
  'search.php' => '搜索',
  'sitemap.php' => '网站地图',
  'error.php' => '错误提示',
  'content/form/add.php' => '提交页',
  'content/form/list.php' => '列表页',
  'content/form/show.php' => '内容页',
  'content/news/list.php' => '列表',
  'content/news/show.php' => '内容',
  'content/page/page.php' => '单页',
  'content/pro/list.php' => '列表',
  'content/pro/show.php' => '内容',
  'block/about.php' => '首页公司简介',
  'content/news/list_pic.php' => '列表_图片',
  'content/job/list.php' => '列表',
  'content/job/show.php' => '内容',
  'block/inner_text.php' => '内页文字介绍',
  'ordershow.php' => '订单详情',
  'bbs/add.php' => '发布主题',
  'bbs/edit.php' => '编辑主题',
  'bbs/index.php' => '主题列表',
  'bbs/myreply.php' => '我的回复',
  'bbs/mytopic.php' => '我的主题',
  'bbs/search.php' => '主题搜索',
  'bbs/show.php' => '帖子内容',
  'city.php' => '城市分站',
);
?>